### ISSUE TITLE
Getting runtime errors casting List<T>

### ISSUE THREAD

**Issue by kevmoo** [isoos/service_worker#17]
With Dart VM version: 2.0.0-dev.53.0+

`promiseToFuture` doesn't work with `List<T>` – you can't just do `value as T` you have to do `(value as List).cast<TItemValue>()`

**Comment by kevmoo** [comment]
Seems only to be in DDC (for now)

**Comment by isoos** [comment]
`dartanalyzer` doesn't report anything on this. What's the caller method that is causing the issue?

**Comment by kevmoo** [comment]
The analyzer wouldn't in the case where T is List<String>

You can't cast List<dynamic> to List<String>

**Comment by lejard-h** [comment]
I am getting this with dart2js

`Uncaught (in promise) Error: CastError: Instance of 'JSArray': type 'JSArray' is not a subtype of type 'List<String>'`

on 2.0.0-dev.64.1

**Comment by isoos** [comment]
@lejard-h: I've published a new version, could you please confirm that it is working for you?

**Comment by lejard-h** [comment]
@isoos it works :+1:  thanks
