### ISSUE TITLE
Provide getter for delegate in ServiceWorkerRegistration

### ISSUE THREAD

**Issue by Janamou** [isoos/service_worker#2]
Hi Istvan,
thank you very much for the great library!

I am now implementing a Firebase cloud messaging to [firebase-dart](https://github.com/firebase/firebase-dart/) and in some point of the time, I would love to have a native JavaScript object for `ServiceWorkerRegistration`. The reason is, that I need to call the [messaging.useServiceWorker()](https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging#useServiceWorker) method in my wrapper which calls the `useServiceWorker()` from JavaScript but I need to have the JavaScript `ServiceWorkerRegistration` object - which is your `facade.ServiceWorkerRegistration`  :-)

And it would be great to have the getter for `_delegate`. Then I can do this:

```dart
import 'package:service_worker/window.dart' as sw;

dynamic useServiceWorker(sw.ServiceWorkerRegistration registration) =>
      jsObject.useServiceWorker(registration.deletage);
```

Would it be a problem to have a getter for `_delegate`?

Thanks!

**Comment by isoos** [comment]
Exposed it as `ServiceWorkerRegistration.jsObject` in #d79a72

**Comment by isoos** [comment]
Thanks for bringing up this use case. I think exposing the JS Object should be the last resort, but in this specific integration it does provide a value that is hard to get around in other ways. I hope it can be the exception than the general pattern.

**Comment by Janamou** [comment]
@isoos Thanks a loooot for this! Works for me! :-)
