### ISSUE TITLE
`Notifiction` is missing the `close()` method

### ISSUE THREAD

**Issue by isoos** [isoos/service_worker#4]
_From @zoechi on May 5, 2017 15:19_

https://github.com/isoos/service_worker/blob/6a5fb0b836713f816ef6040fac01dc9f2868719d/lib/src/js_facade/service_worker_api.dart#L421

_Copied from original issue: isoos/pwa#4_

**Comment by zoechi** [comment]
Thanks a lot for all the super-fast fixes :+1:
