### ISSUE TITLE
Upgrade from comment-based generics syntax

### ISSUE THREAD

**Issue by srawlins** [isoos/service_worker#7]
The comment-based generics syntax will be removed from the Dart SDK tools (like DDC, analyzer) "soon." dart-lang/sdk#28796

Such syntax (like in [Thenable](https://github.com/isoos/service_worker/blob/master/lib/src/js_facade/es6_promise.dart#L15)) needs to be updated, and the minimum Dart SDK in pubspec.yaml needs to be bumped to 1.21, when the [real, non-comment-based syntax was introduced](http://news.dartlang.org/2016/12/dart-121-generic-method-syntax.html).

**Comment by isoos** [comment]
Thanks for the heads-up. I think I'll need to replace and re-do the JS facade objects from the ground up, some of them could be removed completely. Keeping this issue open as a reminder.

**Comment by srawlins** [comment]
Bump. Removal of comment-based generics is coming super soon. Probably February.

**Comment by isoos** [comment]
Fixed in 0.1.2
